/*user_categories*/
INSERT INTO psi_db.user_categories (category_name) VALUES('Administrador general');
INSERT INTO psi_db.user_categories (category_name) VALUES('Administrador institución');

/*users*/
INSERT INTO psi_db.users (first_name,last_name,user_email,password,id_user_categories,company,enabled) VALUES('Juan','PSI','psi@gmail.com','$2a$10$.b3ued627Ub3QhoIlINYg.xVVMkAu17L5QQPwO7jKJqgjk9LqpEt.',1,'PSI Smart Services',1);

/*courses*/
INSERT INTO psi_db.courses (course_name,url,validity,enabled) VALUES('Uso Equipo Autónomo','https://docs.google.com/forms/d/e/1FAIpQLSeQzjZOuGH7xo3egYlT_A0e0BbEF8oH1BW2IB1H-keNh1ZQ6g/viewform',24,1);
INSERT INTO psi_db.courses (course_name,url,validity,enabled) VALUES('Uso Detector 4-5 Gases','https://docs.google.com/forms/d/e/1FAIpQLSee_1n1U8aWbK6_Us_JCUShSIeelBo0Xmy-SfTeSoDw49nfog/viewform?usp=sf_link',24,1);
INSERT INTO psi_db.courses (course_name,url,validity,enabled) VALUES('Trabajo en Altura','https://docs.google.com/forms/d/e/1FAIpQLSdlLvoSeikgKd3ZHOOR9dEG-LoC-MjwzplESZCPBvz2ZFx5Kg/viewform?usp=sf_link',24,1);
INSERT INTO psi_db.courses (course_name,url,validity,enabled) VALUES('Seguridad en el Manejo (4x4)','https://docs.google.com/forms/d/e/1FAIpQLSf8WHgizVdXZ9AU8RyOj2eaOZQ_8USyTKDzb_d3KVj_mkrSwA/viewform?usp=sf_link',24,1);
INSERT INTO psi_db.courses (course_name,url,validity,enabled) VALUES('Seguridad en el Manejo','https://docs.google.com/forms/d/e/1FAIpQLSe4fBm6vUbdV6V9v-zO5sT8G1HWTw3AG4ZyrA8D3_APCwXpzg/viewform?usp=sf_link',24,1);
INSERT INTO psi_db.courses (course_name,url,validity,enabled) VALUES('PLANIFICACIÓN Y PERCEPCIÓN DEL RIESGO - Módulo 4','https://docs.google.com/forms/d/e/1FAIpQLScVghNwxk3ZS6FkDP5NUWj0V7-3Jx4r3fN-nCdZMkcG1805Dw/viewform?usp=sf_link',0,1);
INSERT INTO psi_db.courses (course_name,url,validity,enabled) VALUES('PLANIFICACIÓN Y PERCEPCIÓN DEL RIESGO - Módulo 3','https://docs.google.com/forms/d/e/1FAIpQLSduKHn4Bq-nifjg4SZFhIiJsABswn6hVLbmNXhPc01deTGOsQ/viewform?usp=sf_link',0,1);
INSERT INTO psi_db.courses (course_name,url,validity,enabled) VALUES('PLANIFICACIÓN Y PERCEPCIÓN DEL RIESGO - Módulo 2','https://docs.google.com/forms/d/e/1FAIpQLSdl35FkgjREIkD2Sz-IGdSDo3T9927nyUo0dnIlqr7KbORSDA/viewform?usp=sf_link',0,1);
INSERT INTO psi_db.courses (course_name,url,validity,enabled) VALUES('PLANIFICACIÓN Y PERCEPCIÓN DEL RIESGO - Módulo 1','https://docs.google.com/forms/d/e/1FAIpQLSdl1NikAjwIULG9XQ6MTq6_JRar2aCKEXwmdNlYhoIImiM24w/viewform?usp=sf_link',0,1);
INSERT INTO psi_db.courses (course_name,url,validity,enabled) VALUES('Evaluación Teórica Sulfhídrico','https://docs.google.com/forms/d/e/1FAIpQLSfegs_PVK8s6ppKZx58Dfg252fwmkbx_em-djzTqnJRSWPMAw/viewform?usp=sf_link',24,1);
INSERT INTO psi_db.courses (course_name,url,validity,enabled) VALUES('Espacios Confinados','https://docs.google.com/forms/d/e/1FAIpQLScN_wIBFnpe4-q18h5H7Mk0kE1__4C1REH8APbsrl8F-VVUng/viewform?usp=sf_link',24,1);
INSERT INTO psi_db.courses (course_name,url,validity,enabled) VALUES('CONCIENCIA SITUACIONAL Y PERCEPCION DEL RIESGO - Módulo 3','https://docs.google.com/forms/d/e/1FAIpQLSeDlyNyaoEEoxZHqiUYH0ZX6HQuxqMCqyLItMa_H2BfP4xvKw/viewform?usp=sf_link',0,1);
INSERT INTO psi_db.courses (course_name,url,validity,enabled) VALUES('CONCIENCIA SITUACIONAL Y PERCEPCION DEL RIESGO - Módulo 2','https://docs.google.com/forms/d/e/1FAIpQLSft05Vv_KRXAhkkfg4bAJbC-3LkAhW1Qn2BzPotKozY8bOpQw/viewform?usp=sf_link',0,1);
INSERT INTO psi_db.courses (course_name,url,validity,enabled) VALUES('CONCIENCIA SITUACIONAL Y PERCEPCION DEL RIESGO - Módulo 1','https://docs.google.com/forms/d/e/1FAIpQLSe6uCN8_ayBvDd-qYChbjPKyWnIbkObFjkWUN9aywXx3UnDSg/viewform?usp=sf_link',0,1);

/*documents_templates*/
INSERT INTO psi_db.documents_templates (id_courses,certificate_logo,credential_logo,signature1_image,signature2_image,course_name,credential_forehead,credential_back,certificate_normatives,credential_normatives,enabled) VALUES(1,'DPLUS-LIB-INT.png','PSI-DPLUS-LIBUS-INT.png','sardot1.png','','PERSONAL AUTORIZADO PARA TRABAJOS EN ESPACIOS CONFINADOS Y RESCATE','HABILITACIÓN - ESPACIOS CONFINADOS','ESPACIOS CONFINADOS Y RESCATE','OSHA 29.1910.146 - ANZI Z117.1 - IRAM 3625','OSHA 29.1910.146 - ANZI Z117.1 - IRAM 3626',1);
INSERT INTO psi_db.documents_templates (id_courses,certificate_logo,credential_logo,signature1_image,signature2_image,course_name,credential_forehead,credential_back,certificate_normatives,credential_normatives,enabled) VALUES(2,'DPLUS-LIB-INT.png','PSI-DPLUS-LIBUS-INT.png','sardot1.png','','PERSONAL AUTORIZADO PARA TRABAJOS EN ESPACIOS CONFINADOS Y RESCATE','HABILITACIÓN - ESPACIOS CONFINADOS','ESPACIOS CONFINADOS Y RESCATE','OSHA 29.1910.146 - ANZI Z117.1 - IRAM 3625','OSHA 29.1910.146 - ANZI Z117.1 - IRAM 3626',1);
INSERT INTO psi_db.documents_templates (id_courses,certificate_logo,credential_logo,signature1_image,signature2_image,course_name,credential_forehead,credential_back,certificate_normatives,credential_normatives,enabled) VALUES(3,'DPLUS.png','PSI-DPLUS.png','sardot1.png','','PERSONAL AUTORIZADO PARA TRABAJO SEGURO EN ALTURA Y RESCATE','HABILITACIÓN - TRABAJO EN ALTURA','TRABAJO EN ALTURA','Normativa Nacional e IRAM 3622-3626','Normativa Nacional e IRAM 3622-3627',1);
INSERT INTO psi_db.documents_templates (id_courses,certificate_logo,credential_logo,signature1_image,signature2_image,course_name,credential_forehead,credential_back,certificate_normatives,credential_normatives,enabled) VALUES(4,'boletinOficial.png','logoCredMD.png','baduan.png','sardot2.png','Conducción Defensiva y 4x4','HABILITACIÓN DE MANEJO - FLOTA LIVIANA','CONDUCCIÓN DEFENSIVA Y 4X4','Ley Nacional 19.587 (Dto. 351/73), Ley Nacional N° 24.449 (Dto. N° 779/95), Ley Nacional N° 26.365 (Dto. N°32/18)','Ley Nacional N° 24.449 (Dto. N° 779/95), Ley Nacional N° 26.365 (Dto. N°32/18)',1);
INSERT INTO psi_db.documents_templates (id_courses,certificate_logo,credential_logo,signature1_image,signature2_image,course_name,credential_forehead,credential_back,certificate_normatives,credential_normatives,enabled) VALUES(5,'boletinOficial.png','logoCredMD.png','baduan.png','sardot2.png','Conducción Defensiva','HABILITACIÓN DE MANEJO - FLOTA LIVIANA','CONDUCCIÓN DEFENSIVA','Ley Nacional 19.587 (Dto. 351/73), Ley Nacional N° 24.449 (Dto. N° 779/95), Ley Nacional N° 26.365 (Dto. N°32/18)','Ley Nacional N° 24.449 (Dto. N° 779/95), Ley Nacional N° 26.365 (Dto. N°32/18)',1);
INSERT INTO psi_db.documents_templates (id_courses,certificate_logo,credential_logo,signature1_image,signature2_image,course_name,credential_forehead,credential_back,certificate_normatives,credential_normatives,enabled) VALUES(6,'','psiLogo.png','lugano.png','sardot3,jpg','PLANIFICACIÓN Y PERCEPCIÓN DEL RIESGO','PLANIFICACIÓN','PERCEPCIÓN DEL RIESGO','','',1);
INSERT INTO psi_db.documents_templates (id_courses,certificate_logo,credential_logo,signature1_image,signature2_image,course_name,credential_forehead,credential_back,certificate_normatives,credential_normatives,enabled) VALUES(7,'','psiLogo.png','lugano.png','sardot3,jpg','PLANIFICACIÓN Y PERCEPCIÓN DEL RIESGO','PLANIFICACIÓN','PERCEPCIÓN DEL RIESGO','','',1);
INSERT INTO psi_db.documents_templates (id_courses,certificate_logo,credential_logo,signature1_image,signature2_image,course_name,credential_forehead,credential_back,certificate_normatives,credential_normatives,enabled) VALUES(8,'','psiLogo.png','lugano.png','sardot3,jpg','PLANIFICACIÓN Y PERCEPCIÓN DEL RIESGO','PLANIFICACIÓN','PERCEPCIÓN DEL RIESGO','','',1);
INSERT INTO psi_db.documents_templates (id_courses,certificate_logo,credential_logo,signature1_image,signature2_image,course_name,credential_forehead,credential_back,certificate_normatives,credential_normatives,enabled) VALUES(9,'','psiLogo.png','lugano.png','sardot3,jpg','PLANIFICACIÓN Y PERCEPCIÓN DEL RIESGO','PLANIFICACIÓN','PERCEPCIÓN DEL RIESGO','','',1);
INSERT INTO psi_db.documents_templates (id_courses,certificate_logo,credential_logo,signature1_image,signature2_image,course_name,credential_forehead,credential_back,certificate_normatives,credential_normatives,enabled) VALUES(10,'DPLUS-LIB-INT.png','PSI-DPLUS-LIBUS-INT.png','sardot1.png','','PERSONAL AUTORIZADO PARA TRABAJOS Y SUPERVISIÓN CON SULFHÍDRICO','HABILITACIÓN - TRABAJO CON H2S','TRABAJO Y SUPERVISIÓN H2S','OSHA 29.CFR.1910.1200 - ANZI Z390.1 - IRAM 3606','OSHA 29.CFR.1910.1200 - ANZI Z390.1 - IRAM 3607',1);
INSERT INTO psi_db.documents_templates (id_courses,certificate_logo,credential_logo,signature1_image,signature2_image,course_name,credential_forehead,credential_back,certificate_normatives,credential_normatives,enabled) VALUES(11,'DPLUS-LIB-INT.png','PSI-DPLUS-LIBUS-INT','sardot1.png','','PERSONAL AUTORIZADO PARA TRABAJOS EN ESPACIOS CONFINADOS Y RESCATE','HABILITACIÓN - ESPACIOS CONFINADOS','ESPACIOS CONFINADOS Y RESCATE','OSHA 29.1910.146 - ANZI Z117.1 - IRAM 3625','OSHA 29.1910.146 - ANZI Z117.1 - IRAM 3626',1);
INSERT INTO psi_db.documents_templates (id_courses,certificate_logo,credential_logo,signature1_image,signature2_image,course_name,credential_forehead,credential_back,certificate_normatives,credential_normatives,enabled) VALUES(12,'','psiLogo.png','lugano.png','sardot3.png','CONCIENCIA SITUACIONAL Y PERCEPCIÓN DEL RIESGO','CONCIENCIA SITUACIONAL','PERCEPCIÓN DEL RIESGO','','',1);
INSERT INTO psi_db.documents_templates (id_courses,certificate_logo,credential_logo,signature1_image,signature2_image,course_name,credential_forehead,credential_back,certificate_normatives,credential_normatives,enabled) VALUES(13,'','psiLogo.png','lugano.png','sardot3.png','CONCIENCIA SITUACIONAL Y PERCEPCIÓN DEL RIESGO','CONCIENCIA SITUACIONAL','PERCEPCIÓN DEL RIESGO','','',1);
INSERT INTO psi_db.documents_templates (id_courses,certificate_logo,credential_logo,signature1_image,signature2_image,course_name,credential_forehead,credential_back,certificate_normatives,credential_normatives,enabled) VALUES(14,'','psiLogo.png','lugano.png','sardot3.png','CONCIENCIA SITUACIONAL Y PERCEPCIÓN DEL RIESGO','CONCIENCIA SITUACIONAL','PERCEPCIÓN DEL RIESGO','','',1);

/*profile_images*/
INSERT INTO psi_db.profile_images (dni,image,id_courses) VALUES('41479082','41479082_4.jpg',4);
INSERT INTO psi_db.profile_images (dni,image,id_courses) VALUES('44041892','44041892_4.jpg',4);
INSERT INTO psi_db.profile_images (dni,image,id_courses) VALUES('36434618','36434618_5.jpg',5);
INSERT INTO psi_db.profile_images (dni,image,id_courses) VALUES('33495275','33495275_5.jpg',5);
INSERT INTO psi_db.profile_images (dni,image,id_courses) VALUES('22474765','22474765_5.jpg',5);
INSERT INTO psi_db.profile_images (dni,image,id_courses) VALUES('34293415','34293415_5.jpg',5);
INSERT INTO psi_db.profile_images (dni,image,id_courses) VALUES('24095627','24095627_5.jpg',5);
INSERT INTO psi_db.profile_images (dni,image,id_courses) VALUES('24908582','24908582_5.jpg',5);
INSERT INTO psi_db.profile_images (dni,image,id_courses) VALUES('96189919','96189919_4.jpg',4);
INSERT INTO psi_db.profile_images (dni,image,id_courses) VALUES('33239614','33239614_4.jpg',4);

